import "@/assets/css/globals.css";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import AppThemeProvider from "@/context/ThemeProvider";
import AudioProvider from "@/context/AudioProvider";
import NoFlashThemeScript from "@/components/theme/NoFlashThemeScript";
// import "boxicons";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { arabicFont } from './fonts'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quran Application",
  description: "Generated by create next app",
  author: `Qubartech, ${process.env.name}, Tahir Ahmad`,
  keywords: [`Quran`],
  icons: {
    icon: [
      {
        href: "/quran.svg",
        url: "/quran.svg",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  const themeCookie = cookies().get("__theme__")?.value;
  const isDark =
    themeCookie === "dark" ? true : themeCookie === "light" ? false : undefined;

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${isDark ? "dark" : ""} ${arabicFont.variable}`}
    >
      <head>
        <NoFlashThemeScript />
        <script
          src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"
          async
        ></script>
      </head>
      <body
        className={`${inter.className} bg-gray-100 dark:bg-[#111827]`}
        suppressHydrationWarning
      >
        <AppThemeProvider
          attribute="class"
          defaultTheme={themeCookie ?? "system"}
          enableSystem
          disableTransitionOnChange
        >
          <AudioProvider>
            <Navbar />
            <div className="relative scroll-smooth max-w-screen-2xl mx-auto min-h-screen pt-16">
              {children}
            </div>
            <Footer />
          </AudioProvider>
        </AppThemeProvider>
      </body>
    </html>
  );
}
