import "@/assets/css/globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import AppThemeProvider from "@/context/ThemeProvider";
// import "boxicons";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quran Application",
  description: "Generated by create next app",
  author: `Qubartech, ${process.env.name}, Tahir Ahmad`,
  keywords: [`Quran`],
  icons: {
    icon: [
      {
        href: "/quran.svg",
        url: "/quran.svg",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  const theme = cookies().get("__theme__")?.value || "dark";

  return (
    <html lang="en">
      <head>
        <script
          src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"
          async
        ></script>
      </head>
      <body className={`${inter.className} bg-gray-100 dark:bg-[#111827]`}>
        <AppThemeProvider attribute="class" defaultTheme={theme} enableSystem>
          <Navbar />
          <div className="relative scroll-smooth max-w-screen-2xl mx-auto min-h-screen pt-16">
            {children}
          </div>
          <Footer />
        </AppThemeProvider>
      </body>
    </html>
  );
}
